// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MacGallery
{
	public partial class SeparatorView : NSView
	{
		public SeparatorView (IntPtr handle) : base (handle)
		{
		}
	}
}
