// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MacGallery
{
	public partial class InitialViewController : NSViewController
	{
		public InitialViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
