// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Diagnostics;
using AppKit;
using Foundation;

namespace MacGallery.MainWindow
{
    public partial class WindowController : NSWindowController
    {
        public WindowController(IntPtr handle) : base(handle) { }
    }
}
