// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MacGallery
{
    public partial class DetailViewContainer : NSView
    {
        public override bool AcceptsFirstResponder() => true;

        public DetailViewContainer(IntPtr handle) : base(handle)
        {
        }
    }
}
