// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MacGallery
{
    public partial class OutlineViewController : NSViewController, INSOutlineViewDataSource, INSOutlineViewDelegate
    {
        InitialViewController? initialViewController;

        public NSViewController? ViewControllerForSelection(NSTreeNode[]? selection)
        {
            if (selection is null)
            {
                return initialViewController;
            }

            return selection.Length switch
            {
                0 => initialViewController,
                _ => initialViewController,
            };
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            initialViewController = Storyboard!.InstantiateControllerWithIdentifier(nameof(InitialViewController)) as InitialViewController;
        }

        public OutlineViewController(IntPtr handle) : base(handle)
        {
        }
    }
}
