// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MacGallery
{
    public partial class ImageWindowController : NSWindowController
    {
        public ImageWindowController(IntPtr handle) : base(handle)
        {
        }

        public override void WindowDidLoad()
        {
            base.WindowDidLoad();
            Window.BackgroundColor = NSColor.Black;
            Window.MakeFirstResponder(Window.ContentViewController);
            Window.CollectionBehavior = NSWindowCollectionBehavior.FullScreenPrimary;
            Window.SetFrame(NSScreen.MainScreen.Frame, true);
        }
    }
}
