// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Diagnostics;
using MacGallery.ThumbnailGrid.Models;

namespace MacGallery
{
    public partial class ImageViewController : NSViewController
    {
        private ThumbnailModel? currentThumbnail;

        public void SetCurrentThumbnail(ThumbnailModel? thumbnailModel)
        {
            if (thumbnailModel != null)
            {
                View.Frame = NSScreen.MainScreen.Frame;
                currentThumbnail = thumbnailModel;
                imageView.Image = new NSImage(thumbnailModel.Url);
            }
            else
            {
                // TODO: show error message
            }
        }

        private void DismissWindow()
        {
            this.View.Window.Close();
        }

        public override void KeyDown(NSEvent theEvent)
        {
            var key = (NSKey)theEvent.KeyCode;

            switch (key)
            {
                case NSKey.LeftArrow:
                    SetCurrentThumbnail(ThumbnailStore.GetPrevious(currentThumbnail));
                    break;
                case NSKey.RightArrow:
                    SetCurrentThumbnail(ThumbnailStore.GetNext(currentThumbnail));
                    break;
                case NSKey.Escape:
                    DismissWindow();
                    break;
            }
        }

        public ImageViewController(IntPtr handle) : base(handle)
        {
        }
    }
}
